# Site settings
title: SilverStripe Cheat Sheet
email: ryan@beyondusability.pro
description: >
  SilverStripe Cheat Sheet
baseurl: "/silverstripe-cheatsheet"
url: "http://ryanwachtl.github.io"
twitter_username: ryanwachtl
github_username: ryanwachtl

# Build settings
markdown: kramdown

# Collections
collections:
  - shortdocs