# Site settings
title: SilverStripe Cheat Sheet
email: ryan@beyondusability.pro
description: >
  SilverStripe Cheat Sheet
baseurl: ""
url: "http://silverstripe.shortdocs.co"
twitter_username: ryanwachtl
github_username: ryanwachtl

# Build settings
markdown: kramdown

# Collections
collections:
  - shortdocs